routes/web.php
<?php

use App\Http\Controllers\AdministratorController;
use App\Http\Controllers\DokumenController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KadivController;
use App\Http\Controllers\KegiatanController;
use App\Http\Controllers\KegiatanSubtaskController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::post('login', [\App\Http\Controllers\LoginController::class, 'login'])->name('login');

Route::resources([
    'user' => UserController::class,
    'kegiatan' => KegiatanController::class,
    'subtask' => KegiatanSubtaskController::class,
    'dokumen' => DokumenController::class
]);

Route::get('administrator/manajemen_user', [UserController::class, 'home'])->name('user.manajemen');

Route::get('/user/{id}/ubah_password', [UserController::class, 'ubah_password'])->name('user.update_password');

Route::post('/user/ubah_password', [UserController::class, 'simpan_password'])->name('user.simpan_password');

Route::get('kegiatan/{id}/hapus_anggota', [KegiatanController::class, 'index'])->name('kegiatan.anggota');

Route::get('kegiatan/tandai_selesai/{id}', [KegiatanController::class, 'tandai_selesai'])->name('kegiatan.tandai_selesai');

Route::get('kegiatan/belum_selesai/{id}', [KegiatanController::class, 'belum_selesai'])->name('kegiatan.belum_selesai');

Route::get('cari', [KegiatanController::class, 'cari'])->name('kegiatan.cari');

Route::get('tanggal', [KegiatanController::class, 'cari_tanggal'])->name('kegiatan.cari_tanggal');

Route::post('kegiatan/{id}/tambah_anggota', [KegiatanController::class, 'tambah_anggota_proyek'])->name('kegiatan.tambah_anggota_proyek');

Route::get('kegiatan/{id}/hapus_anggota/{kode}/{id_proyek}', [KegiatanController::class, 'hapus_anggota_proyek'])->name('kegiatan.hapus_anggota');

Route::get('subtask/{id}/kerjakan', [KegiatanSubtaskController::class, 'kerjakan'])->name('subtask.kerjakan');

Route::get('subtask/{id}/pindah_kanan', [KegiatanSubtaskController::class, 'pindah_kanan'])->name('subtask.pindah_kanan');

Route::get('subtask/{id}/pindah_kiri', [KegiatanSubtaskController::class, 'pindah_kiri'])->name('subtask.pindah_kiri');

Route::get('subtask/{id}/destroy', [KegiatanSubtaskController::class, 'destroy'])->name('subtask.destroy');

Route::group(['middleware' => 'checkRole:1'], function () {
    Route::resource('administrator', AdministratorController::class);

    Route::get('/administrator/{id}/ubah_password', [AdministratorController::class, 'ubah_password'])->name('administrator.ubah_password');

    Route::post('user', [UserController::class, 'store'])->name('user.store');

    Route::get('administrator/user/{id}/show', [UserController::class, 'user_detail'])->name('user.detail');
});

Route::group(['middleware' => 'checkRole:2'], function () {
    Route::resource('kadiv', KadivController::class);

    Route::get('/kadiv/{id}/ubah_password', [KadivController::class, 'ubah_password'])->name('kadiv.ubah_password');
});

Route::group(['middleware' => 'checkRole:3'], function () {
    Route::resource('pegawai', PegawaiController::class);

    Route::get('/pegawai/{id}/ubah_password', [PegawaiController::class, 'ubah_password'])->name('pegawai.ubah_password');
});

Route::get('dokumen/{id}-{kode}/download', [DokumenController::class, 'download'])->name('dokumen.download');

Route::get('dokumen/{id}-{kode}/show', [DokumenController::class, 'show'])->name('dokumen.show');

Route::get('dokumen/{id}-{kode}/destroy', [DokumenController::class, 'destroy'])->name('dokumen.destroy');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return Inertia\Inertia::render('Dashboard');
})->name('dashboard');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'note',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function kegiatan() {
        return $this->hasMany(Kegiatan::class, 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Log;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    public function home()
    {
        $user_id = Auth::id();

        $role = DB::table('users')->where('id', $user_id)->value('jabatan_id');

        $users = DB::table('users')->where('deleted_at', null)->orderBy('name')->paginate(20);

        if($role == 1)
        {
            return view('user.index')
                ->with('users', $users);
        }

        return redirect()->back()->with('warning', 'Anda tidak memiliki hak akses');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function index()
    {
        $user_id = Auth::id();

        $role = DB::table('users')->where('id', $user_id)->value('jabatan_id');

        $message = \session('message');

        if($role == '1')
        {
            Session::flash('message', $message);

            return redirect()->route('administrator.home');
        }
        else if($role == '2')
        {
            Session::flash('message', $message);

            return redirect()->route('kegiatan.index');
        }
        else if($role == '3')
        {
            Session::flash('message', $message);

            return redirect()->route('kegiatan.index');
        }
        else
        {
            return view('welcome');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('user.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $id_request = $request->id;

        $result = DB::table('users')->where('id', $id_request)->value('id');

        if($result == null)
        {
            $this->validate($request, [
                'id' => 'required',
                'name' => 'required',
                'email' => 'required',
                'password' => 'required|confirmed',
                'alamat' => 'required',
                'telepon' => 'required',
                'jabatan' => 'required'
            ]);

            $user = new User();

            $user->id = $request->id;
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = bcrypt($request->password);
            $user->alamat = $request->alamat;
            $user->telepon = $request->telepon;
            $user->jabatan_id = $request->jabatan;

            $user->save();

            $log = new Log();
            $log->id_pegawai = Auth::id();
            $log->data = "mendaftarkan akun " . $id_request;
            $log->save();

            $message = "Akun berhasil didaftarkan";

            return redirect()->route('home')->with('message', $message);
        }
        else
        {
            $warning = "ID " . $id_request . " sudah terdaftar. Gunakan nomor ID lain";

            return redirect()->back()->with('warning', $warning);
        }
    }

    public function show($id)
    {
        $role = DB::table('users')->where('id', $id)->value('jabatan_id');

        if($role == '1')
        {
            return redirect()->action([AdministratorController::class, 'show'], $id);
        }
        else if($role == '2')
        {
            return redirect()->action([KadivController::class, 'show'], $id);
        }
        else if($role == '3')
        {
            return redirect()->action([PegawaiController::class, 'show'], $id);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function edit($id)
    {
        $role = DB::table('users')->where('id', $id)->value('jabatan_id');

        if($role == '1')
        {
            return redirect()->action([AdministratorController::class, 'edit'], $id);
        }
        else if($role == '2')
        {
            return redirect()->action([KadivController::class, 'edit'], $id);
        }
        else if($role == '3')
        {
            return redirect()->action([PegawaiController::class, 'edit'], $id);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $user = User::findorFail($id);

        $user->delete();

        Session::flash('message', 'Akun berhasil dihapus');

        return redirect()->action([UserController::class, 'home']);
    }

    public function ubah_password($id)
    {
        $role = DB::table('users')->where('id', $id)->value('jabatan_id');

        if($role == '1')
        {
            return redirect()->action([AdministratorController::class, 'ubah_password'], $id);
        }
        else if($role == '2')
        {
            return redirect()->action([KadivController::class, 'ubah_password'], $id);
        }
        else if($role == '3')
        {
            return redirect()->action([PegawaiController::class, 'ubah_password'], $id);
        }
    }

    public function simpan_password(Request $request)
    {
        /*
         * Menyimpan perubahan password.
         * Dilakukan pengecekan apakah hash password yang lama sesuai dengan yang tersimpan di database.
         */
        $this->validate($request, [
            'old' => 'required',
            'password' => 'required|confirmed'
        ]);

        $user = User::find(Auth::id());

        $hashedPassword = $user->password;

        if (Hash::check($request->old, $hashedPassword)) {
            //Change the password
            $user->fill([
                'password' => Hash::make($request->password)
            ])->save();

            $message = "Password berhasil diubah";

            return redirect()->route('home')->with('message', $message);
        }

        $message = "Password gagal diubah";

        return redirect()->route('home')->with('warning', $message);
    }

    public function user_detail($id)
    {
        $user = User::findorFail($id);

        return view('user.detail')->with('user', $user);
    }
}

resources/views/user/detail.blade.php
@extends('layouts.app')

@section('title')
    Profil {{ $user->name }}
@endsection

{{-- @section('navbar')
    @if(\Illuminate\Support\Facades\Auth::user()->jabatan_id == '1')
        <li class="active"><a href="{{ route('user.manajemen') }}">Manajemen User</a></li>
    @endif
    <li><a href="{{ route('kegiatan.index') }}">Kegiatan</a></li>
@endsection --}}

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Profil {{ $user->name }}</div>

        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>Personnel Number</th>
                    <td>{{ $user->id }}</td>
                </tr>
                <tr>
                    <th>Nama</th>
                    <td>{{ $user->name }}</td>
                </tr>
                <tr>
                    <th>E-Mail</th>
                    <td>{{ $user->email }}</td>
                </tr>
                <tr>
                    <th>Alamat</th>
                    <td>{{ $user->alamat }}</td>
                </tr>
                <tr>
                    <th>Telepon</th>
                    <td>{{ $user->telepon }}</td>
                </tr>
            </table>
            {{ Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) }}
            {{ Form::submit('Hapus Akun', ['class' => 'btn btn-danger', 'onclick' => 'return confirm("Hapus Akun?")']) }}
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title')
    Manajemen User
    @endsection

{{-- @section('navbar')
    @if(\Illuminate\Support\Facades\Auth::user()->jabatan_id == '1')
        <li class="active"><a href="{{ route('user.manajemen') }}">Manajemen User</a></li>
    @endif
    <li><a href="{{ route('kegiatan.index') }}">Kegiatan</a></li>
@endsection --}}

@section('content')
    <div class="col-lg-12">
        <div class="page-header">
            <a href="{{ route('user.create') }}" class="btn btn-default pull-right">User Baru</a>
            <h2>Manajemen User</h2>
        </div>
        {{ $users->links() }}
        <div class="scroll">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Personnel Number</th>
                    <th>Nama</th>
                    <th>E-Mail</th>
                    <th>Alamat</th>
                    <th>Telepon</th>
                    <th>Detail</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->alamat }}</td>
                        <td>{{ $user->telepon }}</td>
                        <td><a href="{{ route('user.detail', $user->id) }}" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Detail</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endsection

resources/views/user/register.blade.php
@extends('layouts.app')

@section('title')
    Register Akun Baru
    @endsection

@section('navbar')
    @if(\Illuminate\Support\Facades\Auth::user()->jabatan_id == '1')
        <li class="active"<a href="{{ route('user.manajemen') }}">Manajemen User</a></li>
    @endif
    {{-- <li><a href="{{ route('kegiatan.index') }}">Kegiatan</a></li> --}}
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="{{ route('user.store') }}">
        {{ csrf_field() }}

        <div class="form-group{{ $errors->has('id') ? ' has-error' : '' }}">
            <label for="id" class="control-label">Personnel Number</label>

            <input id="id" type="text" class="form-control" name="id" value="{{ old('id') }}" required autofocus>

            @if ($errors->has('id'))
                <span class="help-block">
                        <strong>{{ $errors->first('id') }}</strong>
                    </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label for="name" class="control-label">Nama</label>

            <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

            @if ($errors->has('name'))
                <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('alamat') ? ' has-error' : '' }}">
            <label for="alamat" class="control-label">Alamat</label>

            <input id="alamat" type="text" class="form-control" name="alamat" value="{{ old('alamat') }}" required autofocus>

            @if ($errors->has('alamat'))
                <span class="help-block">
                        <strong>{{ $errors->first('alamat') }}</strong>
                    </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('telepon') ? ' has-error' : '' }}">
            <label for="telepon" class="control-label">Telepon</label>

            <input id="telepon" type="text" class="form-control" name="telepon" value="{{ old('telepon') }}" required autofocus>

            @if ($errors->has('telepon'))
                <span class="help-block">
                        <strong>{{ $errors->first('telepon') }}</strong>
                    </span>
            @endif
        </div>

        <div class="form-group">
            {{ Form::label('jabatan', 'Jabatan', ['class' => 'control-label']) }}<br>
            {{ Form::radio('jabatan', '1') }}
            {{ Form::label('administrator', ' Administrator', ['class' => 'control-label']) }}<br>
            {{--{{ Form::radio('jabatan', '2') }}--}}
            {{--{{ Form::label('kepala divisi', ' Kepala Divisi', ['class' => 'control-label']) }}<br>--}}
            {{ Form::radio('jabatan', '3') }}
            {{ Form::label('pegawai', ' Non-Administrator', ['class' => 'control-label']) }}
        </div>

        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
            <label for="email" class="control-label">E-Mail</label>

            <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

            @if ($errors->has('email'))
                <span class="help-block">
                    <strong>{{ $errors->first('email') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
            <label for="password" class="control-label">Password</label>

            <input id="password" type="password" class="form-control" name="password" required>

            @if ($errors->has('password'))
                <span class="help-block">
                        <strong>{{ $errors->first('password') }}</strong>
                    </span>
            @endif
        </div>

        <div class="form-group">
            <label for="password-confirm" class="control-label">Confirm Password</label>

            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">
                Register
            </button>
        </div>
    </form>
    @endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('title')
    Lihat Profil
@endsection

{{-- @section('navbar')
    @if(\Illuminate\Support\Facades\Auth::user()->jabatan_id == '1')
        <li><a href="{{ route('user.manajemen') }}">Manajemen User</a></li>
    @endif
    <li><a href="{{ route('kegiatan.index') }}">Kegiatan</a></li>
@endsection --}}

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Lihat Profil</div>

        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>Personnel Number</th>
                    <td>{{ $user->id }}</td>
                </tr>
                <tr>
                    <th>Nama</th>
                    <td>{{ $user->name }}</td>
                </tr>
                <tr>
                    <th>E-Mail</th>
                    <td>{{ $user->email }}</td>
                </tr>
                <tr>
                    <th>Alamat</th>
                    <td>{{ $user->alamat }}</td>
                </tr>
                <tr>
                    <th>Telepon</th>
                    <td>{{ $user->telepon }}</td>
                </tr>
                {{--<tr>--}}
                    {{--<th>Hak Akses</th>--}}
                    {{--<td>{{ $user->jabatan->nama_jabatan }}</td>--}}
                {{--</tr>--}}
            </table>
            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-warning">Ubah Profil</a>
            <a href="{{ route('user.update_password', $user->id) }}" class="btn btn-default pull-right">Ubah Password</a>
        </div>
    </div>
@endsection

resources/views/user/update_password.blade.php
@extends('layouts.app')

@section('title')
    Ubah Password
    @endsection

@section('navbar')
    @if(\Illuminate\Support\Facades\Auth::user()->jabatan_id == '1')
        <li><a href="{{ route('user.manajemen') }}">Manajemen User</a></li>
    @endif
    <li><a href="{{ route('kegiatan.index') }}">Kegiatan</a></li>
    @endsection

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Ubah Password</div>

        <div class="panel-body">
            <form action="{{ route('user.simpan_password') }}" method="post" role="form" class="form-horizontal">
                {{csrf_field()}}

                <div class="form-group{{ $errors->has('old') ? ' has-error' : '' }}">
                    <label for="password" class="col-md-4 control-label">Password Lama</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="old">

                        @if ($errors->has('old'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('old') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                    <label for="password" class="col-md-4 control-label">Password Baru</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="password">

                        @if ($errors->has('password'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                    <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                    <div class="col-md-6">
                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation">

                        @if ($errors->has('password_confirmation'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-success form-control">Simpan Perubahan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @endsection