routes/web.php
<?php

use App\Http\Controllers\AdministratorController;
use App\Http\Controllers\DokumenController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KadivController;
use App\Http\Controllers\KegiatanController;
use App\Http\Controllers\KegiatanSubtaskController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::post('login', [\App\Http\Controllers\LoginController::class, 'login'])->name('login');

Route::resources([
    'user' => UserController::class,
    'kegiatan' => KegiatanController::class,
    'subtask' => KegiatanSubtaskController::class,
    'dokumen' => DokumenController::class
]);

Route::get('administrator/manajemen_user', [UserController::class, 'home'])->name('user.manajemen');

Route::get('/user/{id}/ubah_password', [UserController::class, 'ubah_password'])->name('user.update_password');

Route::post('/user/ubah_password', [UserController::class, 'simpan_password'])->name('user.simpan_password');

Route::get('kegiatan/{id}/hapus_anggota', [KegiatanController::class, 'index'])->name('kegiatan.anggota');

Route::get('kegiatan/tandai_selesai/{id}', [KegiatanController::class, 'tandai_selesai'])->name('kegiatan.tandai_selesai');

Route::get('kegiatan/belum_selesai/{id}', [KegiatanController::class, 'belum_selesai'])->name('kegiatan.belum_selesai');

Route::get('cari', [KegiatanController::class, 'cari'])->name('kegiatan.cari');

Route::get('tanggal', [KegiatanController::class, 'cari_tanggal'])->name('kegiatan.cari_tanggal');

Route::post('kegiatan/{id}/tambah_anggota', [KegiatanController::class, 'tambah_anggota_proyek'])->name('kegiatan.tambah_anggota_proyek');

Route::get('kegiatan/{id}/hapus_anggota/{kode}/{id_proyek}', [KegiatanController::class, 'hapus_anggota_proyek'])->name('kegiatan.hapus_anggota');

Route::get('subtask/{id}/kerjakan', [KegiatanSubtaskController::class, 'kerjakan'])->name('subtask.kerjakan');

Route::get('subtask/{id}/pindah_kanan', [KegiatanSubtaskController::class, 'pindah_kanan'])->name('subtask.pindah_kanan');

Route::get('subtask/{id}/pindah_kiri', [KegiatanSubtaskController::class, 'pindah_kiri'])->name('subtask.pindah_kiri');

Route::get('subtask/{id}/destroy', [KegiatanSubtaskController::class, 'destroy'])->name('subtask.destroy');

Route::group(['middleware' => 'checkRole:1'], function () {
    Route::resource('administrator', AdministratorController::class);

    Route::get('/administrator/{id}/ubah_password', [AdministratorController::class, 'ubah_password'])->name('administrator.ubah_password');

    Route::post('user', [UserController::class, 'store'])->name('user.store');

    Route::get('administrator/user/{id}/show', [UserController::class, 'user_detail'])->name('user.detail');
});

Route::group(['middleware' => 'checkRole:2'], function () {
    Route::resource('kadiv', KadivController::class);

    Route::get('/kadiv/{id}/ubah_password', [KadivController::class, 'ubah_password'])->name('kadiv.ubah_password');
});

Route::group(['middleware' => 'checkRole:3'], function () {
    Route::resource('pegawai', PegawaiController::class);

    Route::get('/pegawai/{id}/ubah_password', [PegawaiController::class, 'ubah_password'])->name('pegawai.ubah_password');
});

Route::get('dokumen/{id}-{kode}/download', [DokumenController::class, 'download'])->name('dokumen.download');

Route::get('dokumen/{id}-{kode}/show', [DokumenController::class, 'show'])->name('dokumen.show');

Route::get('dokumen/{id}-{kode}/destroy', [DokumenController::class, 'destroy'])->name('dokumen.destroy');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return Inertia\Inertia::render('Dashboard');
})->name('dashboard');

resources/views/layouts/administrator.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.css') }}">
    <link rel="shortcut icon" href="{{ asset('bootstrap/img/favicon.ico') }}">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a href="{{ route('home') }}">
                    <img src="{{ asset('bootstrap/img/logo.png') }}" style="height: 53px; width: 144px; display: inline-block; padding-right: 20px; padding-top: 5px;" class="pull-left" href="{{ route('home') }}">
                </a>

                {{--<a class="navbar-brand" href="{{ route('home') }}">--}}
                {{--Home--}}
                {{--</a>--}}
            </div>

            <div class="collapse navbar-collapse navbar-brand-text" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                {{-- <ul class="nav navbar-nav">
                    @yield('navbar')
                </ul> --}}

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        {{--<li><a href="{{ route('register') }}">Register</a></li>--}}
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('user.show', Auth::user()->id) }}"><span class="glyphicon glyphicon-user"></span> Account</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <span class="glyphicon glyphicon-off"></span> Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
    <div class="banner-navbar"></div>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                @if($errors->any())
                    <div class="alert alert-danger alert-dismissable">
                        @foreach($errors->all() as $error)
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <p>{{ $error }}</p>
                        @endforeach
                    </div>
                @endif

                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ Session::get('message') }}
                    </div>
                @endif

                @if(Session::has('warning'))
                    <div class="alert alert-warning alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ Session::get('warning') }}
                    </div>
                @endif
            </div>
        </div>
    </div>

    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                @yield('content')
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/bootstrap-app.js') }}"></script>
<script src="{{ asset('js/bootbox.min.js') }}"></script>
<script src="{{ asset('js/jquery.jscroll.js') }}"></script>
@yield('js')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

        <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.css') }}">
    <link rel="shortcut icon" href="{{ asset('bootstrap/img/favicon.ico') }}">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a href="{{ route('home') }}">
                        <img src="{{ asset('bootstrap/img/logo.png') }}" style="height: 53px; width: 144px; display: inline-block; padding-right: 20px; padding-top: 5px;" class="pull-left" href="{{ route('home') }}">
                    </a>

                    <a class="navbar-brand" href="{{ route('home') }}">
                        Home
                    </a>
                </div>

                <div class="collapse navbar-collapse navbar-brand-text" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        @yield('navbar')
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            {{--<li><a href="{{ route('register') }}">Register</a></li>--}}
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('user.show', Auth::user()->id) }}"><span class="glyphicon glyphicon-user"></span> Lihat Profil</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <span class="glyphicon glyphicon-off"></span> Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        <div class="banner-navbar"></div>

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @if($errors->any())
                        <div class="alert alert-danger alert-dismissable">
                            @foreach($errors->all() as $error)
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <p>{{ $error }}</p>
                            @endforeach
                        </div>
                    @endif

                    @if(Session::has('message'))
                        <div class="alert alert-success alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ Session::get('message') }}
                        </div>
                    @endif

                        @if(Session::has('warning'))
                            <div class="alert alert-warning alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{ Session::get('warning') }}
                            </div>
                        @endif
                </div>
            </div>
        </div>

        <div class="container">
            <div class="col-lg-12">
                <div class="row">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('/js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-app.js') }}"></script>
    <script src="{{ asset('/js/bootbox.min.js') }}"></script>
    <script src="{{ asset('/js/jquery.jscroll.js') }}"></script>
    @yield('js')
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.2.1/dist/alpine.js" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/kadiv.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.css') }}">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a href="{{ route('home') }}">
                    <img src="{{ asset('bootstrap/img/logo.png') }}" style="height: 60px; width: 160px; display: inline-block; padding-right: 20px; padding-top: 5px;" class="pull-left" href="{{ route('home') }}">
                </a>
                {{--<a class="navbar-brand" href="{{ route('home') }}">--}}
                    {{--Home--}}
                {{--</a>--}}
            </div>

            <div class="collapse navbar-collapse navbar-brand-text" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('user.show', Auth::user()->id) }}"><span class="glyphicon glyphicon-user"></span> Lihat Profil</a>
                                </li>
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <span class="glyphicon glyphicon-log-out"></span> Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
    <div class="banner-navbar"></div>

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @if($errors->any())
                    <div class="alert alert-danger alert-dismissable">
                        @foreach($errors->all() as $error)
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <p>{{ $error }}</p>
                        @endforeach
                    </div>
                @endif

                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ Session::get('message') }}
                    </div>
                @endif

                    @if(Session::has('warning'))
                        <div class="alert alert-warning alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ Session::get('warning') }}
                        </div>
                    @endif
            </div>
        </div>
    </div>

    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                @yield('content')
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="{{ asset('js/bootstrap-app.js') }}"></script>
</body>
</html>

resources/views/layouts/pegawai.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.css') }}">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a href="{{ route('home') }}">
                    <img src="{{ asset('bootstrap/img/logo.png') }}" style="height: 60px; width: 160px; display: inline-block; padding-right: 20px; padding-top: 5px;" class="pull-left" href="{{ route('home') }}">
                </a>
                {{--<a class="navbar-brand" href="{{ route('home') }}">--}}
                    {{--Home--}}
                {{--</a>--}}
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right navbar-brand-text">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('user.show', Auth::user()->id) }}"><span class="glyphicon glyphicon-user"></span> Lihat Profil</a>
                                </li>
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <span class="glyphicon glyphicon-log-out"></span> Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
    <div class="banner-navbar"></div>

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @if($errors->any())
                    <div class="alert alert-danger alert-dismissable">
                        @foreach($errors->all() as $error)
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <p>{{ $error }}</p>
                        @endforeach
                    </div>
                @endif

                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ Session::get('message') }}
                    </div>
                @endif

                    @if(Session::has('warning'))
                        <div class="alert alert-warning alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ Session::get('warning') }}
                        </div>
                    @endif
            </div>
        </div>
    </div>

    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                @yield('content')
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="{{ asset('js/bootstrap-app.js') }}"></script>
</body>
</html>